name: Update README

on:
  push:
  schedule:
    - cron: "0 */8 * * *"
permissions:
  contents: write

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@v5
        with:
          go-version: '^1'

      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated README
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
