name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1'
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated README
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
